# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-28 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypr_ng', '0002_auto_20170217_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('top-blogs', 'Top Blogs'), ('technology', 'Technology')], max_length=125),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='request_outcome',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('declined', 'declined'), ('deferred', 'deferred'), ('dropped', 'dropped')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('contacted', 'contacted'), ('in_progress', 'In progress'), ('closed', 'closed')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='media_marketing_bundles',
            name='caption',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='media_marketing_bundles',
            name='features',
            field=models.TextField(help_text='list all features seperated by semi colon', max_length=2000),
        ),
        migrations.AlterField(
            model_name='media_marketing_bundles',
            name='image',
            field=models.ImageField(upload_to='bundle_tiles'),
        ),
        migrations.AlterField(
            model_name='media_marketing_bundles',
            name='thumbnail',
            field=models.ImageField(upload_to='bundle_thumbnails'),
        ),
        migrations.AlterField(
            model_name='package',
            name='analytics',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, verbose_name='detailed analytics report'),
        ),
        migrations.AlterField(
            model_name='package',
            name='autopost',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, verbose_name='autopost to social media account'),
        ),
        migrations.AlterField(
            model_name='package',
            name='available_on_homepage',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, verbose_name='news made available to journalists, bloggers and researchers via EasyPR homepage'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content_editing',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='content_writing',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='expedited',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, verbose_name='expedited release processing'),
        ),
        migrations.AlterField(
            model_name='package',
            name='featured_package',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='free_consulting',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='google_news_inclusions',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='hyperlinks',
            field=models.CharField(max_length=5, verbose_name='hyperlinks in online press release'),
        ),
        migrations.AlterField(
            model_name='package',
            name='monitoring',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('regular', 'Regular'), ('premium', 'Premium'), ('basic-hp', 'Basic HP'), ('regular-hp', 'Regular HP'), ('basic-fp', 'Basic FP'), ('regular-fp', 'Regular FP'), ('premium-plus', 'Premium Plus')], max_length=75),
        ),
        migrations.AlterField(
            model_name='package',
            name='newsroom',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, verbose_name='Newsroom via EasyPR Media Desk'),
        ),
        migrations.AlterField(
            model_name='package',
            name='notification',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, verbose_name='publication notification via email'),
        ),
        migrations.AlterField(
            model_name='package',
            name='online',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, verbose_name='online_newspaper_publishing'),
        ),
        migrations.AlterField(
            model_name='package',
            name='reuters_news_network',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5),
        ),
        migrations.AlterField(
            model_name='paydetails',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('Diamond Bank', 'Diamond Bank'), ('GTB', 'GTB')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paydetails',
            name='pay_status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='paydetails',
            name='payment_method',
            field=models.CharField(choices=[('Bank Deposit', 'Bank Deposit'), ('Card Payment', 'Card Payment'), ('Bank Transfer', 'Bank Transfer')], default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='paydetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Payment By'),
        ),
        migrations.AlterField(
            model_name='prstrategy',
            name='action_status',
            field=models.CharField(choices=[('new', 'new'), ('contacted', 'contacted'), ('in_progress', 'In progress'), ('closed', 'closed')], default='Contacted', max_length=75),
        ),
        migrations.AlterField(
            model_name='prstrategy',
            name='anon_userID',
            field=models.CharField(max_length=75, verbose_name='Annonymous user ID'),
        ),
        migrations.AlterField(
            model_name='prstrategy',
            name='business_type',
            field=models.CharField(choices=[('NA', 'NA'), ('Company', 'Company'), ('Individual', 'Individual')], default='Company', max_length=25),
        ),
        migrations.AlterField(
            model_name='prstrategy',
            name='company_type',
            field=models.CharField(choices=[('NA', 'NA'), ('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=75),
        ),
        migrations.AlterField(
            model_name='prstrategy',
            name='frequency_of_pr',
            field=models.CharField(choices=[('NA', 'NA'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('several-times-a-month', 'Several Times a Month'), ('quartely', 'Quartely'), ('annually', 'Annually'), ('first-time-user', 'First Time User')], default='monthly', max_length=100),
        ),
        migrations.AlterField(
            model_name='prstrategy',
            name='is_pr_agent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=75),
        ),
        migrations.AlterField(
            model_name='publication',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easypr_ng.MediaPlatform', verbose_name='Media platform'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='press_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easypr_ng.PressMaterial', verbose_name='Media category'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish_online',
            field=models.BooleanField(default=False, verbose_name='Do you also want online publication of the chosen media? '),
        ),
        migrations.AlterField(
            model_name='publication',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easypr_ng.Sector', verbose_name='Media sector'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('sent_to_external_editor', 'sent_to_external_editor'), ('processing', 'processing'), ('published', 'published'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='uploaded_text',
            field=models.FileField(blank=True, null=True, upload_to='publication/text_file'),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publication'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='easypr_ng.PayDetails', verbose_name='Payment details'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='New', max_length=75),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Purchased By'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='Invoices/%Y-%M-%D'),
        ),
        migrations.AlterField(
            model_name='requestbundleservice',
            name='request_outcome',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('declined', 'declined'), ('deferred', 'deferred'), ('dropped', 'dropped')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='requestbundleservice',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('contacted', 'contacted'), ('in_progress', 'In progress'), ('closed', 'closed')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='requestimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_request'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='advert_image_file',
            field=models.FileField(help_text='for newpaper advert submission', null=True, upload_to='uploads/newspaper/advert'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='audio_file',
            field=models.FileField(help_text='for Radio advert submission', null=True, upload_to='uploads/audio/'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='name_of_event',
            field=models.CharField(default='Not Applicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='page_color',
            field=models.CharField(blank=True, choices=[('black and white', 'black and white'), ('color', 'color')], max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_outcome',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('declined', 'declined'), ('deferred', 'deferred'), ('dropped', 'dropped')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='sector',
            field=models.CharField(choices=[('Finance', 'Finance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('contacted', 'contacted'), ('in_progress', 'In progress'), ('closed', 'closed')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='target_media',
            field=models.CharField(choices=[('Newspaper', 'Newspaper'), ('Blog', 'Blog')], max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='uploaded_post_content',
            field=models.FileField(help_text='for blogger distibution submission', upload_to='blogger_distribution'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='video_file',
            field=models.FileField(help_text='for TV advert submission', null=True, upload_to='uploads/video/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='persons_image',
            field=models.FileField(upload_to='testimonial'),
        ),
    ]
