# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-28 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypr_general', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('Kenya', 'Kenya')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('top-blogs', 'Top Blogs'), ('technology', 'Technology')], max_length=75),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(upload_to='blogpost_images'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='banners/services_categories'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(choices=[('Press Release Distribution', 'Press Release Distribution'), ('Content Writing and Marketing', 'Content Marketing'), ('Advertising', 'Advertising'), ('SME Start Up Toolkit', 'SME Start Up Toolkit'), ('Sales and Marketing', 'Sales and Marketing'), ('Events Bureau', 'Events Bureau'), ('Blogger Distribution', 'Blogger Distribution')], default='Press Release Distribution', max_length=175),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='action_type',
            field=models.CharField(choices=[('select_service', 'select service'), ('buy_bundle', 'buy bundle'), ('request_service', 'request service')], default='', max_length=175),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='call_to_action',
            field=models.CharField(blank=True, choices=[('Get Started', 'Get Started'), ('Request Service', 'Request Service'), ('Buy Now', 'Buy Now')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='name',
            field=models.CharField(choices=[('Press Release', 'Press Release Distribution'), ('Photo News', 'Photo News'), ('News Features', 'News Features'), ('Interviews', 'Interviews'), ('Newspapers/Magazines', 'Newspapers/Magazines'), ('Radio Advertising', 'Radio Advertising'), ('TV Advertising', 'TV Advertising'), ('Scripting/Story-Boarding', 'Scripting/Story-Boarding'), ('Audio/Visual content Production', 'Audio/Visual Content Production'), ('Press/Release', 'Press/Release'), ('Feature Articles', 'Feature Articles'), ('Speeches', 'Speeches'), ('Product Reviews', 'Product Reviews'), ('Content Marketing', 'Content Marketing'), ('Brand Design & Logo', 'Brand Design & Logo'), ('Go-to-market Strategy/Consultancy', 'Go-to-market Strategy/Consultancy'), ('Web Development', 'Web Development'), ('Blogger Distribution', 'Blogger distribution'), ('Social Media Influencing', 'Social Media Influencing'), ('Social Media Ads', 'Social Media Ads'), ('Digital Marketing Bundles', 'Digital marketing Bundles'), ('Event Conceptualization', 'Event Conceptualization'), ('Conference/Seminar', 'Conference/Seminar'), ('Sponsorship Bureau', 'Sponsorship Bureau'), ('Speaker Bureau', 'Speaker Bureau')], max_length=150),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='brand_logo',
            field=models.ImageField(upload_to='Client/logo/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], default='', max_length=15),
        ),
    ]
